language: python
python:
#  - "2.6" # StreamHandler
  - "2.7"
#  - "3.2" # because u'' doesn't work
  - "3.3"
  - "pypy"
matrix:
  allow_failures:
    - python: "pypy"
install: pip install coveralls
script:
  - coverage run --branch --source=grammar test.py
after_success:
  - coveralls
