name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - go: 1.16.x
          - go: 1.17.x
          - go: 1.18.x
          - go: 1.x
            experimental: true
    steps:
    - uses: actions/checkout@v3
      with:
        path: src/victorz.ca/grammar
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Install Coveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Install Package
      run: go get -t -v ./...
      working-directory: src/victorz.ca/grammar
    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic
      working-directory: src/victorz.ca/grammar
    - name: Upload coverage
      run: goveralls -coverprofile=coverage.txt -parallel -flagname="$COVERALLS_FLAG_NAME" -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.go }}
      working-directory: src/victorz.ca/grammar

  finish:
    needs: test
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Install Coveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      run: goveralls -parallel-finish -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: codecov.io
      run: bash <(curl -s https://codecov.io/bash)
